### ISSUE TITLE
Description of the tools

### ISSUE THREAD

**Issue by JoelMon** [mjacobus/khtools#8]
What kind of tools for KH users? ;)
From quickly looking through the commits it seems like a talk scheduler with an attendance tracker. 

(Hopes it's has the ability to schedule public talks)

**Comment by mjacobus** [comment]
Hey dear brother :)
As of this moment, only attendance tracker. Lots of lines of code were removed, since this project started off as a fork of https://github.com/mjacobus/territory.

**Comment by mjacobus** [comment]
Hey @JoelMon 

I was looking through my old issues and found this.

So, now it is a more complete tool. I focused in the Portuguese Language only, but here is :

<img width="240" alt="image" src="https://user-images.githubusercontent.com/226834/166127642-27dee4df-516d-4f21-9990-9a4389f6c27d.png">


That is:

- Home Page
- Attendance
- Public talks
  - Talks
  - Congreations
  - Speakers
- Territories
  - Regular
  - Commercial
  - Apartment Buildings
  - Phone Lists
- Field service
  - Area (Neighborhood)
  - Preaching methods (Phone, Letters, house-to-house)
  - Preaching campaigns (Memorial 2021, Letter Xyz)
  - Intercom Type (for apartment buildings)
  - Mail Box Type (for apartment buildings)
  - Phone Carrier
  - Fields Service Group
  - Publisher

**Comment by mjacobus** [comment]
Ah yeah, still no descent README for how to use it.
